<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>BotFramework</AssemblyName>
    <RootNamespace>BotFramework</RootNamespace>
    <OutputType>Library</OutputType>
    <Version>1.0.0</Version>
    <ApplicationIcon>logo.ico</ApplicationIcon>
    <LangVersion>latest</LangVersion>
    <Nullable>disable</Nullable>
    <GamePath>D:\SteamLibrary\steamapps\common\Stardew Valley</GamePath>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Pathoschild.Stardew.ModBuildConfig" Version="4.1.0" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Characters\MovementController.cs" />
  </ItemGroup>

  <ItemGroup>
    <None Include="manifest.json" CopyToOutputDirectory="PreserveNewest" />
    <Content Include="logo.ico" />
  </ItemGroup>

</Project>